### PR TITLE
prettify schedule

### PR DESCRIPTION
**Pull request by 2mol**
🌈

### CODE REVIEW

**Comment by jaspervdj** [comment]
Thanks a lot @2mol!

I took a look at it and would make the following two small tweaks:

1. Drop the 13.00 half-hour hacking block before "tracks", and have lunch until 13.30 each day (I don't think it's a problem that the size of the blocks does not linearly represent time)
2. Also have titles for the blank hacking blocks to make it a bit more clear

Does that sound good?  Happy to discuss if you think it would look better in another way

**Comment by 2mol** [comment]
Agree with 2.

I'll revert lunch to 13:30! Generally I find it more readable if the blocks _do_ correspond linearly to time, it gives me a better feeling at glance where there are the bigger chunks of time. Overall I did not yet find the best way to make it perfectly readable and not too noisy :)

I'll have time to do tweaks the next couple of days.

**Comment by 2mol** [comment]
Like, it would be nice to make it clear that people _can_ get lunch between 12 and 13:30, not that the whole 1.5 hrs are "blocked" off for it.

Here is a tweaked version: https://zurihac-schedule-1--2mol.repl.co/

**Comment by jaspervdj** [comment]
Looks good!  One remaining issue is that it doesn't work very well on mobile.

If I make my screen very narrow, I get something like this:

schedule1

Whereas the current schedule scales a bit better:

schedule2

I think there are some advanced tricks to make the table columns appear below each other if the screen gets too narrow, but that sounds like too much work for what it's worth.  Maybe if we make the Hacking / Tracks columns into one "Hacking & Tracks" column with more text (and the slightly darker red?), it would probably already work better?

Sorry to bikeshed this so much! :-/

**Comment by 2mol** [comment]
No worries, it's not bikeshedding if it's fun. The site will become narrow
on the zfoh site, here I set a minimum widtj for some reason. I'll play
around with it more, combining hacking and tracks sounds good

**Comment by jaspervdj** [comment]
:shipit:

**Pull request merged**
