### PR TITLE
Projects 2020 improvements

### PR DESCRIPTION
**Pull request by 2mol**
Include projects from registration, improve projects page with filtering and displaying levels

### CODE REVIEW

**Comment by nh2** [comment]
Commit message says

```
* remove all 2019 projects, just leave a placeholder
```

but it seems to import the projects from 2019.

**Comment by 2mol** [comment]
I don't think so, but the 2019 projects are still in the subfolder for the old site. In a later commit I took an extract from this year's registrations, so I'm fairly confident that the 2020 json contains the new projects. A quick spot check to last year confirms.

**Comment by nh2** [comment]
I got this from the fact that https://zfoh.ch/zurihac2020/projects.html shows my project `hatrace` even though I haven't added any project for 2020 yet.

**Comment by 2mol** [comment]
Oh, that's good to know! @jaspervdj, can you check if the extract came for sure from the 2020 registrations? [2020-05-09-export.json.zip](https://github.com/zfoh/zfoh.ch/files/4672492/2020-05-09-export.json.zip)

Do you want us to remove hatrace from the list for now Niklas? Is there any possibility you entered it when you registered for this year? If not, then we have to also check all the other projects :)

**Comment by jaspervdj** [comment]
@nh2 This is from the registration data -- I checked the events because I was also confused for a minute that we may have imported the wrong year, but you did specify `hatrace` as a project when you registered in December 2019.  Anyway, feel free to send a PR to remove or expand.

**Comment by nh2** [comment]
@jaspervdj @2mol Ah cool, I didn't know that it was smart enough to do it from the registration. Then all is fine!

**Pull request merged**
